### ISSUE TITLE
"SejongNet" is no longer exist, need to be removed.

### ISSUE THREAD

**Issue by sink772** [icon-project/icon2-docker#54]
https://github.com/icon-project/icon2-docker/blob/47becfb6b468cbae8eeaa1aa143220e237eb1ce3/README.md?plain=1#L39

Also it would be helpful to describe other valid testnet names instead of "SejongNet".

**Comment by JINWOO-J** [comment]
I appreciate your reporting.
Removed unnecessary network information and added new network information.

[https://github.com/icon-project/icon2-docker/commit/15d8417fc8c7e1470064d950cb2a59912c7de88e](url)
